version: "3.9"
services:
  nginx:
    build: ./nginx_service/
    ports:
      - "80:80"
    depends_on:
      - frontend
      - api

  frontend:
    build: ./frontend_service

  redis:
    image: redis

  api:
    build: ./gateway_api/
    env_file:
      - .env
    depends_on:
      - redis
    volumes:
    - ./gateway_api/src/:/app

  summarization_service:
    build: ./summarization_service
    env_file:
      - .env
    depends_on:
      - redis
    volumes:
    - ./hugging_face_hub_cache:/root/.cache/huggingface/hub
